version = 0.1

[default.deploy.parameters]
stack_name = "mnemospark-cost-estimate"
resolve_s3 = true
s3_prefix = "mnemospark-cost-estimate"
region = "eu-north-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "StageName=\"prod\""
image_repositories = []

[default.global.parameters]
region = "eu-north-1"
